GET http://localhost:8080/api/task
###
POST http://localhost:8080/api/task
Content-Type: application/json

{
    "title": "Test",
    "description": "This is a default desc..."
}
###

DELETE http://localhost:8080/api/task/5e5b8030785c3f167ffc540b
Content-Type: application/json
###

PUT http://localhost:8080/api/task/5e5b80e2c0027516fbc66548
Content-Type: application/json

{
    "title": "Update First task title",
    "description": "This is a default desc..."
}

PUT http://localhost:8080/api/task/5e5a8997a481c852dbf833a0/state
Content-Type: application/json

{
    "isDone": true,
}